# Generated by Django 3.1.4 on 2025-07-31 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_add_missing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-date_added'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='leads_agent_organis_v2w3x4_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='leads_agent_user_id_y5z6a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='leads_catego_organis_s9t0u1_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_organis_8b8c8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_organis_9c9d9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_date_ad_1a2b3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_last_co_4d5e6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_email_7g8h9i_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='leads_user_is_orga_j0k1l2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='leads_user_usernam_m3n4o5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='leads_user_email_p6q7r8_idx',
        ),
        migrations.AlterField(
            model_name='agent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., New, Contacted, Converted)', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveIntegerField(help_text='Age of the lead', validators=[django.core.validators.MinValueValidator(0, 'Age cannot be negative.'), django.core.validators.MaxValueValidator(150, 'Age cannot exceed 150.')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='leads.agent'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes about the lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(help_text='Primary email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='First name can only contain letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Last name can only contain letters and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(help_text='Phone number in international format', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an agent.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True, help_text='Designates whether this user is an organizer.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'organisation')},
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['organisation', 'is_active'], name='leads_agent_organis_1069f1_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user'], name='leads_agent_user_id_3abb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['organisation', 'name'], name='leads_categ_organis_03a641_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organisation', 'agent'], name='leads_lead_organis_3c61fa_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organisation', 'category'], name='leads_lead_organis_38b149_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['date_added'], name='leads_lead_date_ad_5111fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_contacted'], name='leads_lead_last_co_b8f2b9_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_lead_email_f663dc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_organisor', 'is_agent'], name='leads_user_is_orga_1b058a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='leads_user_usernam_84ce51_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='leads_user_email_502bc7_idx'),
        ),
    ]
