# Generated by Django 4.2.7 on 2025-08-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_agentperformance_historicallead_leadinteraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('training_samples', models.IntegerField()),
                ('test_samples', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
    ]
