# Generated by Django 4.0 on 2022-02-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newuser',
        ),
    ]
