# Generated by Django 4.0 on 2022-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='phonenumber'),
        ),
    ]
