# Generated by Django 4.0 on 2022-02-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('a', 'approved'), ('n', 'not approved')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
